spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/sneaker_shop
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver